CREATE TABLE Book (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    bookType VARCHAR(255) NOT NULL
);

CREATE TABLE Patron (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE Transaction (
    id INT PRIMARY KEY AUTO_INCREMENT,
    patronEmail VARCHAR(255) NOT NULL,
    bookTitle VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    transactionType VARCHAR(100) NOT NULL,
    date DATE NOT NULL,
    checkReturn VARCHAR(255) NOT NULL,
);
